# Generated by Django 5.2.15 on 2026-06-16 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payments',
            options={'ordering': ['-created_at'], 'verbose_name': 'Paiement', 'verbose_name_plural': 'Paiements'},
        ),
    ]
