# Generated by Django 5.2.15 on 2026-06-16 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorprofile',
            name='certificates_file',
            field=models.FileField(blank=True, null=True, upload_to='media/certificates/'),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='certifications',
            field=models.TextField(blank=True, null=True),
        ),
    ]
