# Generated by Django 5.2.15 on 2026-07-08 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0003_customuser_latitude_customuser_longitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='tutorprofile',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='tutorprofile',
            name='location',
        ),
        migrations.RemoveField(
            model_name='tutorprofile',
            name='longitude',
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ville'),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='country',
            field=models.CharField(blank=True, default='Burundi', max_length=100, verbose_name='Pays'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Adresse Email'),
        ),
        migrations.AlterField(
            model_name='tutorprofile',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='Biographie'),
        ),
        migrations.AlterField(
            model_name='tutorprofile',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name="Vérifie par l'équipe"),
        ),
        migrations.AlterField(
            model_name='tutorprofile',
            name='skills',
            field=models.CharField(help_text='Compétences séparées par des virgules (ex: Python, Design, Réseaux).', max_length=255, verbose_name='Compétences'),
        ),
    ]
