# Generated by Django 5.2.15 on 2026-06-16 11:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categorie', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='choice',
            options={'verbose_name': 'Choix', 'verbose_name_plural': 'Choix'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-created_at'], 'verbose_name': 'Cours', 'verbose_name_plural': 'Cours'},
        ),
        migrations.AlterModelOptions(
            name='enrollment',
            options={'ordering': ['-enrollment_at'], 'verbose_name': 'Inscription', 'verbose_name_plural': 'Inscriptions'},
        ),
        migrations.AlterModelOptions(
            name='lessonprogress',
            options={'verbose_name': 'Progression de la leçon', 'verbose_name_plural': 'Progressions des leçons'},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name': 'Quiz', 'verbose_name_plural': 'Quizzes'},
        ),
        migrations.AlterModelOptions(
            name='quizattempt',
            options={'ordering': ['-attempted_at'], 'verbose_name': 'Tentative de quiz', 'verbose_name_plural': 'Tentatives de quiz'},
        ),
        migrations.AlterUniqueTogether(
            name='quizattempt',
            unique_together={('student', 'quiz')},
        ),
    ]
