# Generated by Django 4.0.10 on 2026-06-12 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_requested', models.DateField()),
                ('time_requested', models.TimeField()),
                ('adress', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'En attente de confirmation'), ('accepted', 'Accepté par le professeur'), ('rejected', 'Rejeté par le professeur'), ('completed', 'Session terminée')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
